services:
  app:
    restart: unless-stopped
    build: .
    tty: true
    ports:
      - ${APP_PORT:-8083}:8083
    volumes:
      - ./api:/api
    command: poetry run litestar --app basic:app run --port 8083 --host 0.0.0.0
    working_dir: /api
    depends_on:
      - redis

  redis:
    hostname: redis
    image: redis:latest
