components:
  schemas: {}
info:
  title: Litestar API
  version: 1.0.0
openapi: 3.1.0
paths:
  /counter/start:
    get:
      deprecated: false
      operationId: CounterStartStartCounter
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
          description: Request fulfilled, document follows
          headers: {}
      summary: StartCounter
  /counter/{id}:
    get:
      deprecated: false
      operationId: CounterIdGetCounter
      parameters:
      - allowEmptyValue: false
        allowReserved: false
        deprecated: false
        in: path
        name: id
        required: true
        schema:
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
          description: Request fulfilled, document follows
          headers: {}
        '400':
          content:
            application/json:
              schema:
                description: Validation Exception
                examples:
                - detail: Bad Request
                  extra: {}
                  status_code: 400
                properties:
                  detail:
                    type: string
                  extra:
                    additionalProperties: {}
                    type:
                    - 'null'
                    - object
                    - array
                  status_code:
                    type: integer
                required:
                - detail
                - status_code
                type: object
          description: Bad request syntax or unsupported method
      summary: GetCounter
  /counter/{id}/end:
    get:
      deprecated: false
      operationId: CounterIdEndEndCounter
      parameters:
      - allowEmptyValue: false
        allowReserved: false
        deprecated: false
        in: path
        name: id
        required: true
        schema:
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
          description: Request fulfilled, document follows
          headers: {}
        '400':
          content:
            application/json:
              schema:
                description: Validation Exception
                examples:
                - detail: Bad Request
                  extra: {}
                  status_code: 400
                properties:
                  detail:
                    type: string
                  extra:
                    additionalProperties: {}
                    type:
                    - 'null'
                    - object
                    - array
                  status_code:
                    type: integer
                required:
                - detail
                - status_code
                type: object
          description: Bad request syntax or unsupported method
      summary: EndCounter
  /counter/{id}/v/{counter}:
    get:
      deprecated: false
      operationId: CounterIdVSetCounter
      parameters:
      - allowEmptyValue: false
        allowReserved: false
        deprecated: false
        in: path
        name: id
        required: true
        schema:
          type: integer
      - allowEmptyValue: false
        allowReserved: false
        deprecated: false
        in: path
        name: counter
        required: true
        schema:
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
          description: Request fulfilled, document follows
          headers: {}
        '400':
          content:
            application/json:
              schema:
                description: Validation Exception
                examples:
                - detail: Bad Request
                  extra: {}
                  status_code: 400
                properties:
                  detail:
                    type: string
                  extra:
                    additionalProperties: {}
                    type:
                    - 'null'
                    - object
                    - array
                  status_code:
                    type: integer
                required:
                - detail
                - status_code
                type: object
          description: Bad request syntax or unsupported method
      summary: SetCounter
servers:
- url: /
